name: Package

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 15.0.2
        if: ${{ runner.os == 'Linux' }}
        uses: joschi/setup-jdk@v2
        with:
          java-version: 15
      - name: Set up JDK 14.0.2
        if: ${{ runner.os == 'Windows' }}
        uses: actions/setup-java@v1
        with:
          java-version: 14.0.2
      - name: Show Build Versions
        run: ./gradlew -v
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: ./gradlew jpackage
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Sparrow Build - ${{ runner.os }}
          path: build/jpackage/*